language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

install:
  - composer install
  - npm install

before_script:
  - |
    git clone -b 2.8.1 git@github.com:squizlabs/PHP_CodeSniffer /tmp/phpcs
    composer install
    scripts/phpcs --config-set installed_paths $TRAVIS_BUILD_DIR

script:
  - /tmp/phpcs/vendor/bin/phpunit --filter HM

cache:
  directories:
    - /tmp/phpcs
